### ISSUE TITLE
GTAGS are not getting generated in the background

### ISSUE THREAD

**Issue by ronakg** [jsfaint/gen_tags.vim#12]
My settings

```
let g:gen_tags#gtags_auto_gen = 1                                                                                                                                                                       
let g:gen_tags#verbose = 1
```

I see the message that it's starting the background process, but nothing happens.

**Comment by jsfaint** [comment]
I can't reproduce this issue on my side  with windows, linux and macOS.
Which OS do you use and the vim version?
If your project is large, it will takes some time to generate gtags file. You need to check if the `gtags` process exist.

**Comment by ronakg** [comment]
I'm running on Ubuntu 16.04.2
Neovim v0.2.0

It only takes 2 seconds when I run `gtags` manually on my project.

**Comment by jsfaint** [comment]
I reproduced this issue on ubuntu16.04.2
It's because `gen_tags.vim` use `gtags -c` to generate gtags
The gtags version on ubuntu16.04.2 is a little old which don't support `-c` option

```bash
$ gtags --version
gtags - GNU GLOBAL 5.7.1

$ gtags -c
gtags: invalid option -- 'c'
Usage: gtags [-iIqvw][-f file][-n number][dbpath]
```

On Archlinux
```
$ gtags --version
gtags (GNU GLOBAL) 6.5.7
```

I searched the GNU global maillist, for some reason (I still don't know) `-c` was remove in 5.7.1 and add back in 5.7.5
http://lists.gnu.org/archive/html/info-global/2009-03/msg00000.html

So that's why gtags generation fail to work on your side.
I'll remove `-c` option for better compatibility.

Thanks for your report which make `gen_tags.vim` getting better 👍

**Comment by jsfaint** [comment]
Hi @ronakg , do you have any update on this issue?
Thanks

**Comment by ronakg** [comment]
It's working fine now. Thanks.
