### ISSUE TITLE
[deoplete][gtags] Error: File does not exists

### ISSUE THREAD

**Issue by joereynolds** [jsfaint/gen_tags.vim#27]
After updating I now get this error, I have `global` installed and `GTAGS` is in the root of my project.
What file is this referring to?

Also it should read as "File does not exist" :)

**Comment by jsfaint** [comment]
Oh, that's because from this commit [ca2fe1b81624d54fd2d726d54efd777b98c16837], the location of `GTAGS` file was changed.
You need to delete your `GTAGS`, `GPATH`, `GRTAGS` and generate it with `:GenGTAGS` command.
Sorry for the inconvenience.

The new location is depends on `g:gen_tags#use_cache_dir`, the default value is 1, the location is `$HOME/.cache/tags_dir`, if this value is set to 0, the location will be `<project dir>/.git/tags_dir`

Please refer #26 

And about that boring error message, I'll remove it later.

**Comment by jsfaint** [comment]
I removed the debug message 😄 
Can you have a try?

**Comment by joereynolds** [comment]
Still seems to work!
Maybe some tests would help prevent regression?

Also what's the benefit of the scm vs cache_dir? Is one more performant than the other?

Thanks for the prompt fixes!

**Comment by jsfaint** [comment]
I always want to add some tests but I'm not familiar with the vimscript test framework.

----

The idea is from @ahmedelgabri in #14 
If the tags is stored in `.git` folder, you can just delete the project folder when you don't need the repo anymore, the tags will be also deleted.
Otherwise, you need to delete tags manually.

**Comment by ahmedelgabri** [comment]
@jsfaint I'm not expert in vim testing too but maybe check https://github.com/w0rp/ale/tree/master/test

**Comment by jsfaint** [comment]
@ahmedelgabri Thanks, I'll have a look later:blush:
